version: '2'
services:
    nginx:
        image: nginx:latest
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./api:/var/www/html"
        ports:
            - 80:80
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - node
    php:
        build:
           context: ./
           dockerfile: ./image/php/Dockerfile
        ports:
          - 9000:9000
        restart: always
        volumes:
            - "./api:/var/www/html"
        links:
          - mysql
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: skl777
            MYSQL_DATABASE: escal_api
            MYSQL_USER: antho
            MYSQL_PASSWORD: antho

        volumes:
            - "./databases:/var/lib/mysql"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        links:
            - php
            - mysql
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: mysql
    node:
        build:
          context: ./
          dockerfile: ./image/node/Dockerfile
        restart: always
        ports:
          - 4200:4200
        volumes:
          - "./front:/usr/src/app"